# Generated by Django 3.2.9 on 2022-01-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='trip_name',
        ),
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(default='Thailand', max_length=100, verbose_name='Trip Name'),
            preserve_default=False,
        ),
    ]
